picks = {
    "away":{
        "afcdiv1":"bengals",
        "afcdiv2":"bills",
        "nfcdiv1":"49ers",
        "nfcdiv2":"rams",
        "afcchamp":"bengals",
        "nfcchamp":"49ers",
        "superbowl":"bengals"
    },
    "home":{
        "afcdiv1":"titans",
        "afcdiv2":"chiefs",
        "nfcdiv1":"packers",
        "nfcdiv2":"bucs",
        "afcchamp":"chiefs",
        "nfcchamp":"rams",
        "superbowl":"rams"
    },
    "Winner":{
        "afcdiv1":"bengals",
        "afcdiv2":"chiefs",
        "nfcdiv1":"49ers",
        "nfcdiv2":"rams",
        "afcchamp":"bengals",
        "nfcchamp":"rams",
        "superbowl":"rams"
    },
    "Grandpa":{
        "nfcdiv1":"packers",
        "nfcdiv2":"bucs",
        "afcdiv1":"titans",
        "afcdiv2":"bills",
        "nfcchamp":"rams",
        "afcchamp":"chiefs",
        "superbowl":"bengals"
    },
    "Michele":{
        "afcdiv1":"",
        "afcdiv2":"",
        "nfcdiv1":"",
        "nfcdiv2":"",
        "nfcchamp":"",
        "afcchamp":"",
        "superbowl":"bengals"
    },
    "Ryan":{
        "nfcdiv1":"packers",
        "nfcdiv2":"rams",
        "afcdiv1":"bengals",
        "afcdiv2":"bills",
        "nfcchamp":"rams",
        "afcchamp":"chiefs",
        "superbowl":"rams"
    },
    "Kerry":{
        "nfcdiv1":"packers",
        "nfcdiv2":"bucs",
        "afcdiv1":"bengals",
        "afcdiv2":"bills",
        "nfcchamp":"rams",
        "afcchamp":"chiefs",
        "superbowl":"rams"
    },
    "Keira":{
        "nfcdiv1":"packers",
        "nfcdiv2":"bucs",
        "afcdiv1":"bengals",
        "afcdiv2":"chiefs",
        "nfcchamp":"rams",
        "afcchamp":"chiefs",
        "superbowl":"bengals"
    },
    "Tegan":{
        "nfcdiv1":"49ers",
        "nfcdiv2":"bucs",
        "afcdiv1":"bengals",
        "afcdiv2":"bills",
        "nfcchamp":"49ers",
        "afcchamp":"chiefs",
        "superbowl":"bengals"
    },
    "Justin":{
        "nfcdiv1":"packers",
        "nfcdiv2":"bucs",
        "afcdiv1":"bengals",
        "afcdiv2":"bills",
        "nfcchamp":"49ers",
        "afcchamp":"chiefs",
        "superbowl":"bengals"
    },
    "Regina":{
        "nfcdiv1":"packers",
        "nfcdiv2":"bucs",
        "afcdiv1":"bengals",
        "afcdiv2":"chiefs",
        "nfcchamp":"49ers",
        "afcchamp":"chiefs",
        "superbowl":"bengals"
    }
}