nfl=Team(id=0, teamname='nfl', league_id=0)
_49ers=Team(id=1, teamname='49ers', league_id=2)
bengals=Team(id=2, teamname='bengals', league_id=1)
bills=Team(id=3, teamname='bills', league_id=1)
bucs=Team(id=4, teamname='bucs', league_id=2)
chiefs=Team(id=5, teamname='chiefs', league_id=1)
packers=Team(id=6, teamname='packers', league_id=2)
rams=Team(id=7, teamname='rams', league_id=2)
titans=Team(id=8, teamname='titans', league_id=1)
db.session.add(nfl)
db.session.add(_49ers)
db.session.add(bengals)
db.session.add(bills)
db.session.add(bucs)
db.session.add(chiefs)
db.session.add(packers)
db.session.add(rams)
db.session.add(titans)
game_1=Game(id=1, game_desc='AFC Divisional Round, Game 1', game_league_id=1, game_round='Division', home_team_id=5, visitor_team_id=3, winner_team_id=5)
game_2=Game(id=2, game_desc='AFC Divisional Round, Game 2', game_league_id=1, game_round='Division', home_team_id=8, visitor_team_id=2, winner_team_id=2)
game_3=Game(id=3, game_desc='NFC Divisional Round, Game 1', game_league_id=2, game_round='Division', home_team_id=6, visitor_team_id=1, winner_team_id=1)
game_4=Game(id=4, game_desc='NFC Divisional Round, Game 2', game_league_id=2, game_round='Division', home_team_id=4, visitor_team_id=7, winner_team_id=7)
game_5=Game(id=5, game_desc='AFC Championship', game_league_id=1, game_round='Conference', home_team_id=5, visitor_team_id=2, winner_team_id=2)
game_6=Game(id=6, game_desc='NFC Championship', game_league_id=2, game_round='Conference', home_team_id=7, visitor_team_id=1, winner_team_id=7)
game_7=Game(id=7, game_desc='Super Bowl', game_league_id=0, game_round='Super Bowl', home_team_id=7, visitor_team_id=2, winner_team_id=7)
db.session.add(game_1)
db.session.add(game_2)
db.session.add(game_3)
db.session.add(game_4)
db.session.add(game_5)
db.session.add(game_6)
db.session.add(game_7)
league_0=League(id=0, name='NFL')
league_1=League(id=1, name='AFC')
league_2=League(id=2, name='NFC')
db.session.add(league_0)
db.session.add(league_1)
db.session.add(league_2)
db.session.commit()